# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableWidget_result = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget_result.setAlternatingRowColors(True)
        self.tableWidget_result.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_result.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_result.setObjectName("tableWidget_result")
        self.tableWidget_result.setColumnCount(0)
        self.tableWidget_result.setRowCount(0)
        self.widget_canvas = QtWidgets.QWidget(self.splitter)
        self.widget_canvas.setMinimumSize(QtCore.QSize(400, 300))
        self.widget_canvas.setObjectName("widget_canvas")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 30))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_op = QtWidgets.QMenu(self.menubar)
        self.menu_op.setObjectName("menu_op")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCalculate = QtWidgets.QAction(MainWindow)
        self.actionCalculate.setObjectName("actionCalculate")
        self.actionDraw = QtWidgets.QAction(MainWindow)
        self.actionDraw.setObjectName("actionDraw")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.menu_file.addAction(self.actionOpen)
        self.menu_file.addAction(self.actionSave)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.actionExit)
        self.menu_op.addAction(self.actionCalculate)
        self.menu_op.addAction(self.actionDraw)
        self.menu_op.addSeparator()
        self.menu_op.addAction(self.actionClear)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_op.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionCalculate)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDraw)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "误差椭圆绘制系统"))
        self.menu_file.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_op.setTitle(_translate("MainWindow", "操作(&O)"))
        self.actionOpen.setText(_translate("MainWindow", "打开(&O)"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "保存结果(&S)"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "退出(&Q)"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionCalculate.setText(_translate("MainWindow", "计算(&C)"))
        self.actionCalculate.setShortcut(_translate("MainWindow", "F5"))
        self.actionDraw.setText(_translate("MainWindow", "绘图(&D)"))
        self.actionDraw.setShortcut(_translate("MainWindow", "F6"))
        self.actionClear.setText(_translate("MainWindow", "清除"))
