# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        self.btn_load = QtWidgets.QPushButton(self.centralWidget)
        self.btn_load.setObjectName("btn_load")
        self.horizontalLayoutButtons.addWidget(self.btn_load)
        self.btn_calc = QtWidgets.QPushButton(self.centralWidget)
        self.btn_calc.setObjectName("btn_calc")
        self.horizontalLayoutButtons.addWidget(self.btn_calc)
        self.btn_save = QtWidgets.QPushButton(self.centralWidget)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayoutButtons.addWidget(self.btn_save)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutButtons)
        self.horizontalLayoutContent = QtWidgets.QHBoxLayout()
        self.horizontalLayoutContent.setObjectName("horizontalLayoutContent")
        self.verticalLayoutLeft = QtWidgets.QVBoxLayout()
        self.verticalLayoutLeft.setObjectName("verticalLayoutLeft")
        self.lbl_input = QtWidgets.QLabel(self.centralWidget)
        self.lbl_input.setObjectName("lbl_input")
        self.verticalLayoutLeft.addWidget(self.lbl_input)
        self.txt_input_view = QtWidgets.QTextEdit(self.centralWidget)
        self.txt_input_view.setReadOnly(True)
        self.txt_input_view.setObjectName("txt_input_view")
        self.verticalLayoutLeft.addWidget(self.txt_input_view)
        self.horizontalLayoutContent.addLayout(self.verticalLayoutLeft)
        self.verticalLayoutRight = QtWidgets.QVBoxLayout()
        self.verticalLayoutRight.setObjectName("verticalLayoutRight")
        self.lbl_output = QtWidgets.QLabel(self.centralWidget)
        self.lbl_output.setObjectName("lbl_output")
        self.verticalLayoutRight.addWidget(self.lbl_output)
        self.table_results = QtWidgets.QTableWidget(self.centralWidget)
        self.table_results.setObjectName("table_results")
        self.table_results.setColumnCount(3)
        self.table_results.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(2, item)
        self.verticalLayoutRight.addWidget(self.table_results)
        self.horizontalLayoutContent.addLayout(self.verticalLayoutRight)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutContent)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "道路纵横断面土方计算软件"))
        self.btn_load.setText(_translate("MainWindow", "导入数据文件 (Load)"))
        self.btn_calc.setText(_translate("MainWindow", "运行土方计算 (Calculate)"))
        self.btn_save.setText(_translate("MainWindow", "导出计算结果 (Save)"))
        self.lbl_input.setText(_translate("MainWindow", "原始数据文件预览："))
        self.lbl_output.setText(_translate("MainWindow", "标准输出计算结果："))
        item = self.table_results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.table_results.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "说明"))
        item = self.table_results.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "计算结果"))
