# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 720)
        MainWindow.setMinimumWidth(1000)

        # ── 菜单动作 ──────────────────────────────────────────
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen.setText("打开(&O)")
        self.actionOpen.setShortcut("Ctrl+O")

        self.actionCalc = QtWidgets.QAction(MainWindow)
        self.actionCalc.setObjectName("actionCalc")
        self.actionCalc.setText("计算(&C)")
        self.actionCalc.setShortcut("Ctrl+C")

        self.actionDraw = QtWidgets.QAction(MainWindow)
        self.actionDraw.setObjectName("actionDraw")
        self.actionDraw.setText("绘图(&D)")
        self.actionDraw.setShortcut("Ctrl+D")

        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave.setText("保存(&S)")
        self.actionSave.setShortcut("Ctrl+S")

        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionClear.setText("清除(&R)")

        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit.setText("退出(&X)")
        self.actionExit.setShortcut("Alt+F4")

        # ── 中心部件 ──────────────────────────────────────────
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")

        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        # ── 左：输入参数区 ────────────────────────────────────
        self.groupInput = QtWidgets.QGroupBox(self.splitter)
        self.groupInput.setObjectName("groupInput")
        self.groupInput.setTitle("输入参数")
        self.formLayout = QtWidgets.QFormLayout(self.groupInput)
        self.formLayout.setObjectName("formLayout")

        self.label_jd = QtWidgets.QLabel(self.groupInput)
        self.label_jd.setObjectName("label_jd")
        self.label_jd.setText("JD 里程 (K+xxx)")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_jd)
        self.edit_jd = QtWidgets.QLineEdit(self.groupInput)
        self.edit_jd.setObjectName("edit_jd")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_jd)

        self.label_r = QtWidgets.QLabel(self.groupInput)
        self.label_r.setObjectName("label_r")
        self.label_r.setText("圆曲线半径 R (m)")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_r)
        self.edit_r = QtWidgets.QLineEdit(self.groupInput)
        self.edit_r.setObjectName("edit_r")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_r)

        # 偏角 α（度分秒三框）
        self.label_alpha = QtWidgets.QLabel(self.groupInput)
        self.label_alpha.setObjectName("label_alpha")
        self.label_alpha.setText("偏角 α (° ′ ″)")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_alpha)

        self.alphaWidget = QtWidgets.QWidget(self.groupInput)
        self.alphaWidget.setObjectName("alphaWidget")
        self.alphaLayout = QtWidgets.QHBoxLayout(self.alphaWidget)
        self.alphaLayout.setContentsMargins(0, 0, 0, 0)
        self.alphaLayout.setObjectName("alphaLayout")

        self.edit_deg = QtWidgets.QLineEdit(self.alphaWidget)
        self.edit_deg.setObjectName("edit_deg")
        self.edit_deg.setPlaceholderText("度")
        self.alphaLayout.addWidget(self.edit_deg)

        self.label_deg = QtWidgets.QLabel(self.alphaWidget)
        self.label_deg.setObjectName("label_deg")
        self.label_deg.setText("°")
        self.alphaLayout.addWidget(self.label_deg)

        self.edit_min = QtWidgets.QLineEdit(self.alphaWidget)
        self.edit_min.setObjectName("edit_min")
        self.edit_min.setPlaceholderText("分")
        self.alphaLayout.addWidget(self.edit_min)

        self.label_min = QtWidgets.QLabel(self.alphaWidget)
        self.label_min.setObjectName("label_min")
        self.label_min.setText("′")
        self.alphaLayout.addWidget(self.label_min)

        self.edit_sec = QtWidgets.QLineEdit(self.alphaWidget)
        self.edit_sec.setObjectName("edit_sec")
        self.edit_sec.setPlaceholderText("秒")
        self.alphaLayout.addWidget(self.edit_sec)

        self.label_sec = QtWidgets.QLabel(self.alphaWidget)
        self.label_sec.setObjectName("label_sec")
        self.label_sec.setText("″")
        self.alphaLayout.addWidget(self.label_sec)

        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.alphaWidget)

        # 指定桩号
        self.label_stake = QtWidgets.QLabel(self.groupInput)
        self.label_stake.setObjectName("label_stake")
        self.label_stake.setText("指定桩号 (K+xxx)")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_stake)
        self.edit_stake = QtWidgets.QLineEdit(self.groupInput)
        self.edit_stake.setObjectName("edit_stake")
        self.edit_stake.setPlaceholderText("输入待求桩号")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_stake)

        # ── 右：结果表格 + 示意图 ──────────────────────────────
        self.rightPanel = QtWidgets.QWidget(self.splitter)
        self.rightPanel.setObjectName("rightPanel")
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightPanel)
        self.rightLayout.setObjectName("rightLayout")

        self.tableResult = QtWidgets.QTableWidget(self.rightPanel)
        self.tableResult.setObjectName("tableResult")
        self.tableResult.setMinimumHeight(280)
        self.rightLayout.addWidget(self.tableResult)

        self.groupDraw = QtWidgets.QGroupBox(self.rightPanel)
        self.groupDraw.setObjectName("groupDraw")
        self.groupDraw.setTitle("曲线示意图")
        self.groupDraw.setMinimumHeight(220)
        self.drawLayout = QtWidgets.QVBoxLayout(self.groupDraw)
        self.drawLayout.setObjectName("drawLayout")

        self.labelDraw = QtWidgets.QLabel(self.groupDraw)
        self.labelDraw.setObjectName("labelDraw")
        self.labelDraw.setText("请先计算，再点击「绘图」")
        self.labelDraw.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDraw.setMinimumHeight(200)
        self.labelDraw.setFrameShape(QtWidgets.QFrame.Box)
        self.drawLayout.addWidget(self.labelDraw)

        self.rightLayout.addWidget(self.groupDraw)

        # ── 装配布局 ──────────────────────────────────────────
        self.splitter.setSizes([280, 880])
        self.mainLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)

        # ── 菜单栏：文件 / 计算 / 绘图 三个独立菜单 ──────────
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")

        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")

        self.menuCalc = QtWidgets.QMenu(self.menubar)
        self.menuCalc.setObjectName("menuCalc")

        self.menuDraw = QtWidgets.QMenu(self.menubar)
        self.menuDraw.setObjectName("menuDraw")

        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCalc.menuAction())
        self.menubar.addAction(self.menuDraw.menuAction())

        # 文件菜单
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)

        # 计算菜单
        self.menuCalc.addAction(self.actionCalc)

        # 绘图菜单
        self.menuDraw.addAction(self.actionDraw)

        # ── 工具栏 ────────────────────────────────────────────
        self.toolbar = QtWidgets.QToolBar(MainWindow)
        self.toolbar.setObjectName("toolbar")
        self.toolbar.setMovable(False)
        self.toolbar.addAction(self.actionOpen)
        self.toolbar.addAction(self.actionCalc)
        self.toolbar.addAction(self.actionDraw)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.actionSave)
        self.toolbar.addAction(self.actionClear)
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)

        # ── 状态栏 ────────────────────────────────────────────
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "道路曲线要素计算与里程桩计算程序设计"))
        self.groupInput.setTitle(_translate("MainWindow", "输入参数"))
        self.label_jd.setText(_translate("MainWindow", "JD 里程 (K+xxx)"))
        self.label_r.setText(_translate("MainWindow", "圆曲线半径 R (m)"))
        self.label_alpha.setText(_translate("MainWindow", "偏角 α (° ′ ″)"))
        self.label_deg.setText(_translate("MainWindow", "°"))
        self.label_min.setText(_translate("MainWindow", "′"))
        self.label_sec.setText(_translate("MainWindow", "″"))
        self.label_stake.setText(_translate("MainWindow", "指定桩号 (K+xxx)"))
        self.groupDraw.setTitle(_translate("MainWindow", "曲线示意图"))
        self.labelDraw.setText(_translate("MainWindow", "请先计算，再点击「绘图」"))
        self.menuFile.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menuCalc.setTitle(_translate("MainWindow", "计算(&C)"))
        self.menuDraw.setTitle(_translate("MainWindow", "绘图(&D)"))
        self.actionOpen.setText(_translate("MainWindow", "打开(&O)"))
        self.actionCalc.setText(_translate("MainWindow", "计算(&C)"))
        self.actionDraw.setText(_translate("MainWindow", "绘图(&D)"))
        self.actionSave.setText(_translate("MainWindow", "保存(&S)"))
        self.actionClear.setText(_translate("MainWindow", "清除(&R)"))
        self.actionExit.setText(_translate("MainWindow", "退出(&X)"))
        self.toolbar.setWindowTitle(_translate("MainWindow", "工具栏"))
